{"uuid": "a73977e1-74ee-409a-a3a6-54ba8211d1a7", "children": ["23e3137d-bfbc-4e85-ad99-f1ff09235c37"], "befores": [{"name": "setup_login_uno", "status": "passed", "start": 1666753955271, "stop": 1666753964932}], "afters": [{"name": "setup_login_uno::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x00851ED3+2236115]\n\tOrdinal0 [0x007E92F1+1807089]\n\tOrdinal0 [0x006F65C0+812480]\n\tOrdinal0 [0x0071A3FD+959485]\n\tOrdinal0 [0x0071B71F+964383]\n\tGetHandleVerifier [0x00AFE7E2+2743074]\n\tGetHandleVerifier [0x00AF08D4+2685972]\n\tGetHandleVerifier [0x008E2BAA+532202]\n\tGetHandleVerifier [0x008E1990+527568]\n\tOrdinal0 [0x007F080C+1837068]\n\tOrdinal0 [0x007F4CD8+1854680]\n\tOrdinal0 [0x007F4DC5+1854917]\n\tOrdinal0 [0x007FED64+1895780]\n\tBaseThreadInitThunk [0x763BFA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x77827BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x77827B8E+238]\n\n", "trace": "  File \"C:\\Users\\hectordc\\PycharmProjects\\PRACTICAS_UDEMY\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 209, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\hectordc\\PycharmProjects\\PRACTICAS_UDEMY\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 909, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\hectordc\\PycharmProjects\\PRACTICAS_UDEMY\\Maquina_uno\\MV1\\PYTEST\\Fixture_decorade2.py\", line 43, in setup_login_uno\n    driver.close()\n  File \"C:\\Users\\hectordc\\PycharmProjects\\PRACTICAS_UDEMY\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 551, in close\n    self.execute(Command.CLOSE)\n  File \"C:\\Users\\hectordc\\PycharmProjects\\PRACTICAS_UDEMY\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\hectordc\\PycharmProjects\\PRACTICAS_UDEMY\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1666754013173, "stop": 1666754013209}], "start": 1666753955271, "stop": 1666754013210}